import Header from "@/components/header/Header";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import React from "react";
import { store } from "@/store";
import { StoreProvider } from "@/store/StoreProvider";
import { getProducts } from "@/store/productsStore";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await store.dispatch(getProducts());
  const { products } = store.getState().products;

  return (
    <html lang="en">
      <body className="relative min-h-screen">
        <StoreProvider
          preloadedState={{
            products: { products },
          }}
        >
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
